; globals in system RAM
.global rng_base
.global rng_out
.global rng_alt
.global rng_tail
.global area_code
.global town_code
.global palace_code
.global lives_remaining
.global region_number
.global world_number
.global game_mode
.global PRG_bank

; bank 0 exports
.global bank0_Manual_Save_Game_Routine_UP_AND_A
.global bank0_Return_of_Ganon_screen_Palettes
.global bank0_unknown1
.global bank0_unknown2
.global bank0_unknown27
.global bank0_unknown28
.global bank0_unknown37
.global bank0_unknown39
.global bank0_unknown4
.global bank0_unknown12
.global bank0_903A
.global bank0_96A8
.global bank0_9925
.global bank0_9A04
.global bank0_A199
.global bank0_A256
.global bank0_A30F
.global bank0_A315
.global bank0_A329
.global bank0_A334
.global bank0_A338
.global bank0_A82A
.global Chandeliers_in_North_Castle
.global Check_for_Fire_Spell
.global Hub_Update_Routine
.global Initialization_stuff
.global LevelUp_Pane__BlankLine_SecondHalfOnly
.global Side_View_Initialization_when_entering_a_Key_Area
.global Some_Palettes_Data_related_to_Falling_Animation
.global Spell_Casting_Routine
.global Tables_for_Game_Over_screen_text
.global overworld3
.global overworld4
.global startup_init_begin_game

; bank 1 exports
.global bank1_Transform_completed_palaces_into_stone
.global bank1_Check_for_Hidden_Palace_spot

; bank 3 exports
.global bank3_B082
.global bank3_Door_Destinations_in_Towns
.global bank3_Build_a_pointer_with_86_and_a_value_from_C643
.global bank3_Small_Objects_Construction_Routine
.global bank3_Object_Construction_Routine

; bank 4 exports
.global bank4_Palettes
.global bank4_Palettes_for_Palaces1
.global bank4_Palettes_for_Palaces2
.global bank4_Palettes_for_Palaces3
.global bank4_Palettes_for_Palaces4
.global bank4_Palettes_for_Palaces5
.global bank4_Palettes_for_Palaces6
.global bank4_Palaces_Type_A_B_Palettes
.global bank4_Unknown_Palettes
.global bank4_Build_a_pointer_with_81_and_a_value_from_10165

; bank 5 exports
.global bank5_8B69
.global bank5_code4
.global bank5_routines_related_to_Ending_sequence
.global bank5_9764
.global bank5_PowerON__Reset_Memory
.global bank5_A610
.global bank5_B9CA
.global bank5_Build_a_pointer_with_81_and_a_value_from_14177
.global bank5_Object_Construction_Routine
.global bank5_Small_Objects_Construction_Routine

; bank 6 exports
.global bank6_Title_Music_Tick
.global bank6_Game_Music_Tick

; bank 7 exports
.global bank7_Change_Enemy_Facing_Direction_and_X_Velocity
.global bank7_Check_for_Hidden_Palace_spot_Bank_1
.global bank7_Controllers_Input
.global bank7_Desert_Rocks_initialization_routine
.global bank7_Determine_Enemy_Facing_Direction_relative_to_Link
.global bank7_Display
.global bank7_Enemy_Routines1_Ache_and_Acheman
.global bank7_Enemy_Routines1_Bago_Bago0
.global bank7_Enemy_Routines1_Bago_Bago1
.global bank7_Enemy_Routines1_Bago_Bago_Generator
.global bank7_Enemy_Routines1_Bit
.global bank7_Enemy_Routines1_Bot
.global bank7_Enemy_Routines1_Deeler
.global bank7_Enemy_Routines1_Elevator
.global bank7_Enemy_Routines1_Fairy
.global bank7_Enemy_Routines1_Locked_Door
.global bank7_Enemy_Routines1_Moa
.global bank7_Enemy_Routines1_Myu
.global bank7_Enemy_Routines1_Octorok
.global bank7_Enemy_Routines1_Raising_Bubbles
.global bank7_Enemy_Routines1_Red_Jar
.global bank7_Enemy_Routines2_Ache_and_Acheman
.global bank7_Enemy_Routines2_BagoBago
.global bank7_Enemy_Routines2_Bot_and_Bit
.global bank7_Enemy_Routines2_Deeler
.global bank7_Enemy_Routines2_Elevator
.global bank7_Enemy_Routines2_Fairy
.global bank7_Enemy_Routines2_LockedDoor
.global bank7_Enemy_Routines2_Moa
.global bank7_Enemy_Routines2_Myu
.global bank7_Enemy_Routines2_Octorok
.global bank7_Enemy_Routines2_RedJar
.global bank7_Enemy_Routines2_unknown
.global bank7_Enemy_Stops_when_Hit
.global bank7_Erase_Name_Tables_0and1__set_scroll_to_0_0
.global bank7_Floor_Y_Position
.global bank7_Gravity
.global bank7_Link_Collision_Detection
.global bank7_Link_Hit_Routine
.global bank7_Links_Display_Routine
.global bank7_Mute_music_when_loading_between_areas
.global bank7_NMI_Entry_Point
.global bank7_Overworld_Boundaries__Mountain_or_Water_Bank_1
.global bank7_PowerON_code
.global bank7_PullAddrFromTableFollowingThisJSR_withIndexOfA_then_JMP
.global bank7_Remove_All_Sprites
.global bank7_Remove_All_Sprites_except_Sprite0
.global bank7_Reset_Memory_Ranges
.global bank7_Set_0E_0F_pointer_according_to_Object_Group
.global bank7_Set_Memory_300_4FF_and_00_DF_to_Zero
.global bank7_Set_RAM_Address_for_Object0E0F
.global bank7_Set_Ram_Addy_for_Object__0E_0F
.global bank7_Set_tile_and_go_down_1_row_in_2x2_tiles_units
.global bank7_Set_tile_and_move_right_1_column
.global bank7_Simple_Horizontal_Movement
.global bank7_Simple_Vertical_Movement
.global bank7_Spawn_New_Projectile
.global bank7_Sword_Hit_Detection_maybe__probably_part_of_it_at_least
.global bank7_Turn_Palaces_into_Stone_Bank_1
.global bank7_XY_Movements_Routine
.global bank7_applyGravityMotion
.global bank7_code2
.global bank7_code33
.global bank7_code34
.global bank7_code37
.global bank7_code39
.global bank7_code43
.global bank7_code44
.global bank7_code45
.global bank7_code49
.global bank7_code51
.global bank7_code55
.global bank7_forest_chop_with_hammer
.global bank7_idem__maybe
.global bank7_remove_enemy_or_item
.global bank7_LD2EC
.global bank7_irq
.global Set_Item_RAM_bit_to_0__Bits_0_3
.global bank7_Title_Music_Tick
.global LCB18_fill_hp_or_mp_to_full__provide_x_register__maybe
.global bank7_C24F
.global bank7_DFDB
.global bank7_DF01
.global bank7_DF3F
.global bank7_E024
.global bank7_DFD2
.global bank7_DFD1
.global bank7_E001
.global bank7_C72D
.global bank7_DF56
.global bank7_EC02
.global bank7_C2A6
.global bank7_E726
.global bank7_E187
.global bank7_D55E
.global bank7_D20A
.global bank7_DAC7
.global bank7_DD3D
.global bank7_DE3D
.global bank7_DE40
.global bank7_DECE
.global bank7_DED4
.global bank7_DF4C
.global bank7_E3B9
.global bank7_E469
.global bank7_E48A
.global bank7_E563
.global bank7_E94C
.global bank7_F0CC
.global bank7_F0D7
.global bank7_F1F4
.global bank7_DE6C
.global bank7_E48B
.global bank7_E4D9
.global bank7_E617
.global bank7_EA1C
.global bank7_EA32
.global bank7_C258
.global bank7_D000
.global bank7_DF58
.global bank7_E579
.global bank7_E942
.global bank7_EA14
.global bank7_F0C6
.global bank7_C722
.global bank7_CF05
.global bank7_D168
.global bank7_D174
.global bank7_D293
.global bank7_E5B2
.global bank7_EA18
.global bank7_EF08
.global bank7_F2D3
.global bank7_FCA5
