.global PPU_CTRL
.global PPU_MASK
.global PPU_STATUS
.global OAM_ADDR
.global OAM_DATA
.global PPU_SCROLL
.global PPU_ADDR
.global PPU_DATA

.global SQ1_VOL
.global SQ1_SWEEP
.global SQ1_LO
.global SQ1_HI
.global SQ2_VOL
.global SQ2_SWEEP
.global SQ2_LO
.global SQ2_HI
.global TRI_LINEAR
.global TRI_LO
.global TRI_HI
.global NOISE_VOL
.global NOISE_LO
.global NOISE_HI
.global DMC_FREQ
.global DMC_RAW
.global DMC_START
.global DMC_LEN
.global OAM_DMA
.global SND_CHN
.global JOY1
.global JOY2
